# CONFIGURE_FOR_IOS_10_3 will configure the BUILD_TARGET for an ARM64/iOS 10.3 device
FUNCTION(CONFIGURE_FOR_IOS_10_3 IOS_BUILD_TARGET)
  SET_TARGET_PROPERTIES(${IOS_BUILD_TARGET} PROPERTIES
    XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT "dwarf-with-dsym"
    XCODE_ATTRIBUTE_GCC_PRECOMPILE_PREFIX_HEADER "YES"
    XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "10.3"
    XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iOS Developer"
    XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "XXXX"
    XCODE_ATTRIBUTE_ORGANIZATIONNAME "OpenMapper"
    XCODE_ATTRIBUTE_SDKROOT "iphoneos10.3"
    XCODE_ATTRIBUTE_GCC_SYMBOLS_PRIVATE_EXTERN YES
    XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC YES
    XCODE_ATTRIBUTE_COMBINE_HIDPI_IMAGES "NO"
    XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2"
    XCODE_ATTRIBUTE_VALID_ARCHS "arm64")
ENDFUNCTION(CONFIGURE_FOR_IOS_10_3)
