dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc

# Configuration variables. All variables are global now, but this can be used to
# trigger a build matrix for different ROS distributions if desired.
env:
  global:
    - ROS_DISTRO=kinetic
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    # - CI_SOURCE_PATH=$(pwd)
    # - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    # - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    # - ROS_PARALLEL_JOBS='-j8 -l6'

################################################################################

# Install system dependencies, namely a very barebones ROS setup.
before_install:
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  #- sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  #- source /opt/ros/$ROS_DISTRO/setup.bash
  # Prepare rosdep to install dependencies.
  #- sudo rosdep init
  #- rosdep update
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - ros-kinetic-opencv3 		# opencv3
      - ros-kinetic-eigen-conversions 	# eigen3
      - python-dev 			# TODO(gocarlos) is this really needed
      - python-numpy 			# TODO(gocarlos) is this really needed
      # - libeigen3-dev
# before_script:
  # install openCV
#   - git clone https://github.com/opencv/opencv.git
#   - cd opencv
#   - mkdir build
#   - cd build
#   - cmake ..
#   - make -j4
#   - sudo make -j4 install
#   - cd ../..



script:

  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - ./build.sh
  - ./test.sh
